name = "Lean at MC2020"
version = "0.1"
extra_files = "extras"
intro = "src/game_files"

[[worlds]]
name = "Irrationality of sqrt 2"
id = 1
levels = [
	"game_files/sqrt2/sq_eq_zero1.lean",
	"game_files/sqrt2/sq_eq_zero2.lean",
	"game_files/sqrt2/two_div.lean",
]

[[worlds]]
name = "the empty world"
id = 2
parents = [1]
levels = [
]
